version: 2
registries:
  public-nuget:
    type: nuget-feed
    url: https://api.nuget.org/v3/index.json
  space-nuget:
    type: nuget-feed
    url: https://nuget.pkg.github.com/vmetreveli/index.json
    username: ${{ secrets.NUGET_USER_GITHUB }}
    password: ${{secrets.NUGET_SECRET_GITHUB}}
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    registries: "*"
    schedule:
      interval: "daily"
      time: "09:00"
    open-pull-requests-limit: 100
   
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
    open-pull-requests-limit: 100
